// atomic/pages/Question/index.vue
<template>
  <div class="panel-container">
    <nuc-entity-chart-card
      entity="Question"
      class="annual-chart-card"
      chart-method-type="annual"
      type="bar"
      :direction="isMobile() ? 'horizontal' : 'vertical'"
      :data="{ question: results }"
      :loading="loading"
    />
    <nuc-question-dashboard
      :data="results"
      :get-data="getAllQuestions"
      :loading="loading"
    />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'

import { questionRequests, useNucDialog } from 'nucleify'

const { closeDialog } = useNucDialog()

const { results, loading, getAllQuestions } = questionRequests(closeDialog)

onMounted(() => {
  getAllQuestions(true)
})
</script>

// atomic/pages/question.tsx
'use client'

import { useEffect } from 'react'

import {
  isMobile,
  NucEntityChartCard,
  NucQuestionDashboard,
  questionRequests,
  useNucDialog,
} from 'nucleify'

export function NucQuestionPage(): React.JSX.Element {
  const { closeDialog } = useNucDialog()
  const { results, loading, getAllQuestions } = questionRequests(
    closeDialog,
    'next'
  )

  useEffect(() => {
    void getAllQuestions(true)
  }, [])

  return (
    <div className="panel-container">
      <NucEntityChartCard
        entity="Question"
        chartClass="annual-chart-card"
        chartMethodType="annual"
        type="bar"
        direction={isMobile() ? 'horizontal' : 'vertical'}
        data={{ question: results }}
        loading={loading}
      />
      <NucQuestionDashboard
        data={results ?? []}
        getData={getAllQuestions}
        loading={loading}
      />
    </div>
  )
}
